name:                idk-how-to-define-constructors-in-haskell
version:             0.1.0.0
github:              "toku-sa-n/idk-how-to-define-constructors-in-haskell"
license:             BSD3
author:              "Hiroki Tokunaga"
maintainer:          "tokusan441@gmail.com"
copyright:           "2023 Hiroki Tokunaga"

synopsis:            The document describing several ways to define constructors in Haskell

description:         Please see the README on GitHub at <https://github.com/toku-sa-n/idk-how-to-define-constructors-in-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- hspec

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -pgmL markdown-unlit

library:
  source-dirs: src

tests:
  idk-how-to-define-constructors-in-haskell:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - idk-how-to-define-constructors-in-haskell
